version: '3.8'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es01
    networks:
      - elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin  # Password per l'utente elastic (superuser)
    stdin_open: true
    tty: true
    volumes:
      - ./esdata:/usr/share/elasticsearch/data  # Mappa la cartella locale './esdata' ai dati di Elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - es01
    volumes:
      - ./kibana-data:/usr/share/kibana/data  # Mappa la cartella locale './kibana-data' ai dati di Kibana
   
  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.1
    container_name: logstash
    networks:
      - elastic
    ports:
      - "5044:5044"  # Porta per input Logstash (ad esempio, Beats)
    volumes:
    - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Configurazione Logstash
    - ./logstash/csvdata:/usr/share/logstash/data                         # File CSV
    - ./logstash/output:/usr/share/logstash/output                        # Directory per output 
    depends_on:
      - es01
networks:
  elastic:
    driver: bridge
